version: "3.7"
services:
  mock:
    build: mock-server
    ports:
      - "8090:8090"
    hostname: localhost
    networks:
      - "payment-system"
  payment-service:
    build: payment-service
    ports:
      - "8080:8080"
    hostname: localhost
    networks:
      - "payment-system"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.1
    container_name: mysql-payment-sys
    ports:
      - 3306:3306
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    networks:
      - "payment-system"
networks:
  payment-system: {}


