version: "3.7"
services:
  mock:
    build: mock-server
    ports:
      - "8090:8090"
    hostname: localhost
    networks:
      - "payment-system"
  mysql:
    image: mysql:latest
    container_name: mysql-payment-sys
    ports:
      - 3306:3306
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    networks:
      - "payment-system"
  payment-service:
    build: payment-service
    ports:
      - "8080:8080"
    hostname: localhost
    networks:
      - "payment-system"
    depends_on:
      - mysql
    command: ["/home/files/mock/wait-for-it.sh", "-t", "10", "-s", "localhost:3306", "--", "java","-jar", "/home/files/mock/payment-service-1.0-SNAPSHOT.jar"]
networks:
  payment-system: {}


