spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true
    url: jdbc:mysql://localhost:3306/test
    user: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:/db/changelog/db.changelog-master.yaml

contract:
  external:
    bill:
      inquiry:
        providerA:
          url: http://localhost:8090/bill